import pandas as pd
import io
import xlsxwriter

# ==========================================
# 1. CORE CALCULATION (Engine Universal)
# ==========================================
def hitung_rab_lengkap(kode_ahsp, uraian, volume, satuan, 
                       koef_tenaga, harga_tenaga, 
                       koef_bahan, harga_bahan, 
                       koef_alat, harga_alat, 
                       persen_overhead=15.0):
    """
    Menghitung HSP (Harga Satuan Pekerjaan) Full sesuai Permen PUPR.
    Support: SDA, Bina Marga, & Cipta Karya.
    
    Args:
        koef_tenaga (dict): {'Pekerja': 0.5, 'Mandor': 0.05}
        harga_tenaga (dict): {'Pekerja': 100000, 'Mandor': 150000}
        ... dan seterusnya untuk Bahan & Alat.
    """
    
    # --- 1. Hitung Sub-Total Tenaga (A) ---
    total_tenaga = 0.0
    for nama, koef in koef_tenaga.items():
        # .get(nama, 0) mencegah error jika harga lupa diinput user
        harga = harga_tenaga.get(nama, 0) 
        total_tenaga += float(koef) * float(harga)

    # --- 2. Hitung Sub-Total Bahan (B) ---
    total_bahan = 0.0
    for nama, koef in koef_bahan.items():
        harga = harga_bahan.get(nama, 0)
        total_bahan += float(koef) * float(harga)

    # --- 3. Hitung Sub-Total Alat (C) ---
    total_alat = 0.0
    for nama, koef in koef_alat.items():
        harga = harga_alat.get(nama, 0)
        total_alat += float(koef) * float(harga)

    # --- 4. Rekapitulasi (Total HSP) ---
    jumlah_dasar = total_tenaga + total_bahan + total_alat
    
    # Hitung Overhead (Maks 15% sesuai Permen PUPR)
    nilai_overhead = jumlah_dasar * (persen_overhead / 100)
    
    # Harga Satuan Pekerjaan (HSP) Final
    hsp_jadi = jumlah_dasar + nilai_overhead
    
    # Total Harga per Item (HSP x Volume)
    total_harga_proyek = hsp_jadi * float(volume)

    # Return Dictionary Lengkap (Untuk ditampilkan di Tabel/Excel)
    return {
        "meta": {
            "kode": kode_ahsp, 
            "uraian": uraian, 
            "satuan": satuan, 
            "volume": volume
        },
        "biaya": {
            "tenaga": total_tenaga, 
            "bahan": total_bahan, 
            "alat": total_alat,
            "jumlah_dasar": jumlah_dasar, 
            "overhead": nilai_overhead,
            "hsp": hsp_jadi, 
            "total_final": total_harga_proyek
        }
    }

# ==========================================
# 2. EXPORT TO EXCEL (Professional Formatter)
# ==========================================
def export_to_excel(df_boq):
    """
    Mengubah Dataframe RAB menjadi File Excel Siap Cetak.
    """
    output = io.BytesIO()
    workbook = xlsxwriter.Workbook(output, {'in_memory': True})
    worksheet = workbook.add_worksheet("RAB_Export")

    # --- Style Formatting ---
    fmt_header = workbook.add_format({'bold': True, 'bg_color': '#D7E4BC', 'border': 1, 'align': 'center', 'valign': 'vcenter', 'text_wrap': True})
    fmt_currency = workbook.add_format({'num_format': '#,##0', 'border': 1, 'valign': 'vcenter'})
    fmt_text = workbook.add_format({'border': 1, 'valign': 'vcenter', 'text_wrap': True})
    fmt_center = workbook.add_format({'border': 1, 'align': 'center', 'valign': 'vcenter'})
    fmt_title = workbook.add_format({'bold': True, 'size': 14})
    
    # --- Header Dokumen ---
    worksheet.write('A1', 'REKAPITULASI RENCANA ANGGARAN BIAYA (RAB)', fmt_title)
    worksheet.write('A2', 'Generated by: JIAT Smart Studio (AHSP 2025)', workbook.add_format({'italic': True}))
    
    # --- Header Tabel ---
    headers = ['No', 'Kode Analisa', 'Uraian Pekerjaan', 'Vol', 'Sat', 'HSP (Rp)', 'Total Harga (Rp)']
    for col, h in enumerate(headers):
        worksheet.write(4, col, h, fmt_header)

    # --- Isi Data (Looping) ---
    total_proyek = 0
    row_idx = 5 # Mulai baris ke-6
    
    for i, row in df_boq.iterrows():
        worksheet.write(row_idx, 0, i+1, fmt_center)
        worksheet.write(row_idx, 1, row['kode_ahsp'], fmt_center)
        worksheet.write(row_idx, 2, row['uraian'], fmt_text)
        worksheet.write(row_idx, 3, row['volume'], fmt_center)
        worksheet.write(row_idx, 4, row['satuan'], fmt_center)
        worksheet.write(row_idx, 5, row['harga_satuan'], fmt_currency)
        worksheet.write(row_idx, 6, row['total'], fmt_currency)
        total_proyek += row['total']
        row_idx += 1

    # --- Footer Total ---
    worksheet.merge_range(row_idx, 0, row_idx, 5, "TOTAL KESELURUHAN (Termasuk PPN/Overhead)", fmt_header)
    worksheet.write(row_idx, 6, total_proyek, fmt_currency)

    # --- Finishing (Lebar Kolom) ---
    worksheet.set_column('A:A', 5)   # No
    worksheet.set_column('B:B', 15)  # Kode
    worksheet.set_column('C:C', 50)  # Uraian (Lebar)
    worksheet.set_column('D:E', 10)  # Vol/Sat
    worksheet.set_column('F:G', 20)  # Harga

    workbook.close()
    return output.getvalue()
